Models/Spot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace work_01.Models
{
    public class Spot
    {
        public int SpotId { get; set; }
        [Required,Display(Name = "Spot Name"),StringLength(50)]
        public string SpotName { get; set; }

        //nev
        public ICollection<BookingEntry> BookingEntries { get; set; }= new List<BookingEntry>();

    }
}

Controllers/SpotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using work_01.Models;

namespace work_01.Controllers
{
    public class SpotsController : Controller
    {
        private BookingDbContext db = new BookingDbContext();

        // GET: Spots
        public ActionResult Index()
        {
            return View(db.Spots.ToList());
        }

        // GET: Spots/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spots.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        // GET: Spots/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Spots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SpotId,SpotName")] Spot spot)
        {
            if (ModelState.IsValid)
            {
                db.Spots.Add(spot);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(spot);
        }

        // GET: Spots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spots.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        // POST: Spots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SpotId,SpotName")] Spot spot)
        {
            if (ModelState.IsValid)
            {
                db.Entry(spot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(spot);
        }

        // GET: Spots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spot spot = db.Spots.Find(id);
            if (spot == null)
            {
                return HttpNotFound();
            }
            return View(spot);
        }

        // POST: Spots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Spot spot = db.Spots.Find(id);
            db.Spots.Remove(spot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Spots/Create.cshtml
@model work_01.Models.Spot

@{
    ViewBag.Title = "Create";
}

<h2 class="display-4">Add New Spot</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SpotName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SpotName, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
            </div>
            <div class="col-md-4">

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary btn-sm mt-2">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    <a href="@Url.Action("Index","Spots")" class="btn btn-link btn-sm" style="text-decoration:none;"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
</div>

Views/Spots/Delete.cshtml
@model work_01.Models.Spot

@{
    ViewBag.Title = "Delete";
}



<h3 class="display-4 alert alert-danger">Are you sure you want to delete this spot?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SpotName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpotName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href="@Url.Action("Index","Spots")" class="btn btn-link btn-sm" style="text-decoration:none;"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
        </div>
    }
</div>

Views/Spots/Details.cshtml
@model work_01.Models.Spot

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Spot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SpotName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpotName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SpotId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Spots/Edit.cshtml
@model work_01.Models.Spot

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Spot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SpotId)

        <div class="form-group">
            @Html.LabelFor(model => model.SpotName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpotName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpotName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Spots/Index.cshtml
@model IEnumerable<work_01.Models.Spot>

@{
    ViewBag.Title = "Index";
}

<h2 class="display-4">Spot List</h2>

<p class="d-flex justify-content-end">
    <a href="@Url.Action("Create","Spots")" class="btn btn-primary btn-sm"><i class="fa fa-plus-circle"></i> Add New Spot</a>
</p>
<table class="table table-bordered table-striped table-sm">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SpotName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SpotName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SpotId }, new { @class = "btn btn-success btn-sm" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.SpotId }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>